# 📁 traefik/traefik.yml
# Fichier de configuration statique de Traefik. Active l'interface dashboard, le provider Docker, et Let's Encrypt.
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true  # Active le dashboard Traefik (accès via :8088/dashboard)
  insecure: true    # Désactive la sécurité pour le dashboard (à sécuriser en prod)

dockers:
  endpoint: "unix:///var/run/docker.sock"  # Permet à Traefik de lire les conteneurs Docker en temps réel
  exposedByDefault: false                   # Empêche l’exposition automatique des conteneurs sans label

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@example.com"
      storage: "/etc/traefik/acme.json"     # Stocke les certificats SSL ici
      httpChallenge:
        entryPoint: web
